### ISSUE TITLE
ParentOrganisationalUnit default OU string should come from configuration

### ISSUE THREAD

**Issue by simoncrelling** [captainqwerty/Account-Creation-Tools#2]
ActiveDirectorySearcher.cs

**Comment by captainqwerty** [comment]
Currently testing a fix.
Have to get an if statement involved.

**Comment by captainqwerty** [comment]
Tested and working resolution.
It has to be a constant in the method declaration so can't directly use the config file, so it's default value is null and it does a quick if check that if its null it uses the default if not it skips over it.
